apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts
spec:
  selector:
    matchLabels:
      app: test-sts
  serviceName: "test-sts"
  replicas: 1
  template:
    metadata:
      labels:
        app: test-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: alpine
        image: alpine:latest
        command:
          - sleep
          - infinity
        ports:
        - containerPort: 5234
        volumeMounts:
        - name: test-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: test-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard-delete"
      resources:
        requests:
          storage: 2Gi
