apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpuconsumer
    project: cpuconsumer
    version: v1
  name: cpuconsumer
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cpuconsumer
      name: cpuconsumer
      project: cpuconsumer
      version: v1
  template:
    metadata:
      annotations:
        nosidecar.istio.io/inject: "false"
      labels:
        app: cpuconsumer
        name: cpuconsumer
        project: cpuconsumer
        version: v1
    spec:
      containers:
      - name: cpuconsumer
        image: prune/cpuconsumer:v0.0.1
        imagePullPolicy: Always
        env:
          - name: "NUMCPU"
            value: "1"
          - name: "TESTDURATION"
            value: "10m"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 100Mi
          requests:
            cpu: 1
            memory: 100Mi
