apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpuconsumer
    project: cpuconsumer
    version: v1
    app.kubernetes.io/name: cpuconsumer
  name: cpuconsumer
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cpuconsumer
      name: cpuconsumer
      project: cpuconsumer
      version: v1
  template:
    metadata:
      annotations:
        nosidecar.istio.io/inject: "false"
      labels:
        app: cpuconsumer
        name: cpuconsumer
        project: cpuconsumer
        version: v1
    spec:
      containers:
      - name: cpuconsumer
        image: prune/cpuconsumer:v0.0.2
        imagePullPolicy: Always
        env:
          - name: "WAITCPU"
            value: "0.1"
          - name: "WORKCPU"
            value: "3"
          - name: "WAITDURATION"
            value: "5m"
          - name: "WORKDURATION"
            value: "5m"
          # - name: "GOMAXPROCS"
          #   value: "1"
        ports:
        - containerPort: 7789
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1.5"
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      nodeSelector:
        node.kubernetes.io/instance-type: n2d-highmem-4
      tolerations:
      - key: "dedicated"
        value: "infra-ops"
        effect: "NoSchedule"