apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-debug
  name: golang-debug
  namespace: prune
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: golang-debug
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang-debug
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: golang:alpine
        imagePullPolicy: IfNotPresent
        name: golang
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            cpu: "1"
            memory: 16Gi
          requests:
            cpu: "1"
            memory: 16Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0