{
 "title": "Container CPU Usage vs Throttling Percentage VM",
 "description": "Detect/Diagnose CPU throttling for containers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[2m])",
     "legendFormat": "CPU Cores Usage {{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage vs Throttling Percent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod, container) ((container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"} / container_cpu_cfs_periods_total{cluster=\"$cluster\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"}) * 100)",
     "legendFormat": "Throttle Percent {{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage vs Throttling Percent Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,pod, container) ((irate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"}[2m]) / irate(container_cpu_cfs_periods_total{cluster=\"$cluster\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"}[2m])) * 100)",
     "legendFormat": "Throttle Percent {{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage vs Requests Percent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"}[2m]))\n/\nsum by (namespace, pod, container) (kube_pod_container_resource_requests{cluster=\"$cluster\",resource=\"cpu\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}} / {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage vs Limit Percent",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"}[2m]))\n/\nsum by (namespace, pod, container) (kube_pod_container_resource_limits{cluster=\"$cluster\",resource=\"cpu\",container=~\"$container\", pod=~\"$pod\", namespace=\"$namespace\"})",
     "legendFormat": "{{namespace}} / {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "CPU Consumer threads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cpuconsumer_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Consumer Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(cpuconsumer_ops[1m])", "legendFormat": "{{pod}} ({{gomaxprocs}})" },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Consumer threads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}